modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kotlinforforge"
type = "required"
versionRange = "${loader_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "railways"
type = "optional"
versionRange = "[0.3.0-alpha.2+neoforge-mc1.21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "pantographsandwires"
type = "optional"
versionRange = "[1.21.1-beta-0.2.2-C6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "framedblocks"
type = "optional"
versionRange = "[10.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "copycats"
type = "optional"
versionRange = "[3.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "worldedit"
type = "optional"
versionRange = "[7.3.8,)"
ordering = "AFTER"
side = "BOTH"
