plugins {
	id("java-library")
	id("maven-publish")
	id("idea")
	id("net.neoforged.moddev") version "2.0.95"
	kotlin("jvm")
}

val modId = "railx"
val neoVersion = "21.1.209"

neoForge {
	version = neoVersion
	
	parchment {
		mappingsVersion = "2024.11.17"
		minecraftVersion = libs.versions.minecraft
	}
	
	runs {
		register("client") {
			client()
			gameDirectory = project.file("../forge/run")
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
			
			// jvmArguments.add("-Dmixin.debug.export=true")
		}
		
		configureEach {
			// Recommended logging data for a userdev environment
			// The markers can be added/remove as needed separated by commas.
			// "SCAN": For mods scan.
			// "REGISTRIES": For firing of registry events.
			// "REGISTRYDUMP": For getting the contents of all registries.
			systemProperty("forge.logging.markers", "REGISTRIES")
			
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}
}

// Include resources generated by data generators.
sourceSets.main.configure {
	resources.srcDir("src/generated/resources")
}

repositories {
	val central = mavenCentral()
	remove(central)
	add(0, central)
	
	exclusiveContent {
		forRepository { maven(url = "https://api.modrinth.com/maven") }
		filter { includeGroup("maven.modrinth") }
	}
	
	maven(url = "https://thedarkcolour.github.io/KotlinForForge/") {
		name = "Kotlin for Forge"
		content { includeGroup("thedarkcolour") }
	}
	
	maven(url = "https://maven.createmod.net/") {
		content {
			includeGroup("com.simibubi.create")
			includeGroup("dev.engine-room.flywheel")
			includeGroup("net.createmod.catnip")
			includeGroup("net.createmod.ponder")
		}
	}
	
	maven(url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/") {
		content { includeGroup("fuzs.forgeconfigapiport") }
	}
	
	maven(url = "https://mvn.devos.one/snapshots") {
		content {
			includeGroup("com.tterrag.registrate")
		}
	}
	
	maven(url = "https://squiddev.cc/maven/") {
		content {
			includeGroup("cc.tweaked")
			includeGroup("org.squiddev")
		}
	}
	
	maven(url = "https://repo.spongepowered.org/repository/maven-public/") {
		name = "Sponge"
		content {
			includeGroup("org.spongepowered")
		}
	}
}

dependencies {
	implementation("com.simibubi.create:create-${libs.versions.minecraft.get()}:6.0.6-98:slim") {
		isTransitive = false
	}
	
	implementation("net.createmod.ponder:Ponder-NeoForge-${libs.versions.minecraft.get()}:1.0.56")
	// compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${libs.versions.minecraft.get()}:1.0.4-27")
	implementation("dev.engine-room.flywheel:flywheel-neoforge-${libs.versions.minecraft.get()}:1.0.4-27")
	implementation("com.tterrag.registrate:Registrate:MC1.21-1.3.0+62")
	
	// for mod compatibility
	compileOnly("maven.modrinth:framedblocks:10.4.0")
	compileOnly("maven.modrinth:copycats:3.0.2+mc.1.21.1-neoforge")
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		isDownloadSources = false
		isDownloadJavadoc = false
	}
}

tasks.configureEach {
	if(name.startsWith("idea")) notCompatibleWithConfigurationCache("Intellij does not supports")
}
