@file:Suppress("UnstableApiUsage")

plugins {
	id("java-library")
	id("maven-publish")
	id("idea")
	id("net.neoforged.moddev") version "2.0.95"
	kotlin("jvm")
}

val modId = "railx"
val neoVersion = "21.1.209"

version = "1.0-SNAPSHOT"

base {
	archivesName = modId
}

val runClientSources by sourceSets.registering {
	configurations {
		get(compileClasspathConfigurationName).extendsFrom(compileClasspath.get())
		get(runtimeClasspathConfigurationName).extendsFrom(runtimeClasspath.get())
	}
	tasks {
		named(classesTaskName) { dependsOn(classes) }
		named(processResourcesTaskName) { dependsOn(processResources) }
	}
}

neoForge {
	version = neoVersion
	
	parchment {
		mappingsVersion = "2024.11.17"
		minecraftVersion = libs.versions.minecraft
	}
	
	mods {
		register(modId) {
			sourceSet(sourceSets.main.get())
		}
	}
	
	accessTransformers {
		file("src/main/resources/META-INF/accesstransformer.cfg")
	}
	
	runs {
		register("client") {
			client()
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
			
			sourceSet = runClientSources
			// jvmArguments.add("-Dmixin.debug.export=true")
		}
		
		register("server") {
			server()
			programArgument("--nogui")
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("gameTestServer") {
			type = "gameTestServer"
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("data") {
			data()
			
			// example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
			gameDirectory = project.file("run-data")
			
			// Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
			val existingMods = listOf("create")
			
			programArguments.addAll(
				"--mod", modId,
				"--all",
				"--output", file("src/generated/resources/").absolutePath,
				"--existing", file("src/main/resources/").absolutePath,
				*existingMods.flatMap { listOf("--existing-mod", it) }.toTypedArray(),
			)
		}
		
		configureEach {
			// Recommended logging data for a userdev environment
			// The markers can be added/remove as needed separated by commas.
			// "SCAN": For mods scan.
			// "REGISTRIES": For firing of registry events.
			// "REGISTRYDUMP": For getting the contents of all registries.
			systemProperty("forge.logging.markers", "REGISTRIES")
			
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}
}

// Include resources generated by data generators.
sourceSets.main.configure {
	resources.srcDir("src/generated/resources")
}

repositories {
	val central = mavenCentral()
	remove(central)
	add(0, central)
	
	exclusiveContent {
		forRepository { maven(url = "https://api.modrinth.com/maven") }
		filter { includeGroup("maven.modrinth") }
	}
	
	maven(url = "https://thedarkcolour.github.io/KotlinForForge/") {
		name = "Kotlin for Forge"
		content { includeGroup("thedarkcolour") }
	}
	
	maven(url = "https://maven.createmod.net/") {
		content {
			includeGroup("com.simibubi.create")
			includeGroup("dev.engine-room.flywheel")
			includeGroup("net.createmod.catnip")
			includeGroup("net.createmod.ponder")
		}
	}
	
	maven(url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/") {
		content { includeGroup("fuzs.forgeconfigapiport") }
	}
	
	maven(url = "https://mvn.devos.one/snapshots") {
		content {
			includeGroup("com.tterrag.registrate")
		}
	}
	
	maven(url = "https://squiddev.cc/maven/") {
		content {
			includeGroup("cc.tweaked")
			includeGroup("org.squiddev")
		}
	}
	
	maven(url = "https://maven.enginehub.org/repo/") {
		content { includeGroupAndSubgroups("com.sk89q") }
	}
	
	maven(url = "https://repo.spongepowered.org/repository/maven-public/") {
		name = "Sponge"
		content {
			includeGroup("org.spongepowered")
		}
	}
}

dependencies {
	fun runClientOnly(dependencyNotation: Any) =
		add(runClientSources.get().runtimeOnlyConfigurationName, dependencyNotation)
	
	fun optionalModDependency(dependencyNotation: Any): Dependency? {
		val dependency = compileOnly(dependencyNotation) ?: return null
		return add(runClientSources.get().runtimeOnlyConfigurationName, dependency)
	}
	
	implementation(project(":cc-asm"))
	
	// kfflib>=5.8.0 won't resolve extension functions: https://github.com/thedarkcolour/KotlinForForge/issues/131
	compileOnly("thedarkcolour:kotlinforforge-neoforge:5.7.0")
	runtimeOnly("thedarkcolour:kotlinforforge-neoforge:5.10.0")
	
	implementation("com.simibubi.create:create-${libs.versions.minecraft.get()}:6.0.6-98:slim") {
		isTransitive = false
	}
	
	implementation("net.createmod.ponder:Ponder-NeoForge-${libs.versions.minecraft.get()}:1.0.56")
	// compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${libs.versions.minecraft.get()}:1.0.4-27")
	implementation("dev.engine-room.flywheel:flywheel-neoforge-${libs.versions.minecraft.get()}:1.0.4-27")
	implementation("com.tterrag.registrate:Registrate:MC1.21-1.3.0+62")
	
	// for mod compatibility
	optionalModDependency("maven.modrinth:framedblocks:10.4.0")
	optionalModDependency("maven.modrinth:copycats:3.0.2+mc.1.21.1-neoforge")
	optionalModDependency("maven.modrinth:xaeros-world-map:1.39.12_NeoForge_1.21")
	
	// optional mod dependencies
	compileOnly("com.sk89q.worldedit:worldedit-neoforge-mc1.21:7.3.8") {
		exclude(group = "com.google.guava", module = "guava") // version conflict
	}
	
	runClientOnly("maven.modrinth:worldedit:7.3.8")
}

file("build/mod_output_path.txt").let { output ->
	val jar: Jar by tasks
	if(output.exists()) {
		val copyModJarToServer by tasks.registering(Copy::class) {
			from(jar)
			into(output.readText().trim())
		}
		jar.finalizedBy(copyModJarToServer)
	}
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
	var replaceProperties = mapOf(
		"minecraft_version" to libs.versions.minecraft.get(),
		"minecraft_version_range" to "[1.21.1,1.22)",
		"neo_version" to neoVersion,
		"neo_version_range" to "[21,)",
		"loader_version_range" to "[5.3,)",
		"mod_id" to modId,
		"mod_name" to "RailX",
		"mod_license" to "All Rights Reserved",
		"mod_version" to "$version",
		"mod_authors" to "lhwdev",
		"mod_description" to "This is good mod",
	)
	
	inputs.properties(replaceProperties)
	expand(replaceProperties)
	from("src/main/templates")
	into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.configure {
	resources.srcDir(generateModMetadata)
}
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		isDownloadSources = true
		isDownloadJavadoc = true
	}
}

tasks.configureEach {
	if(name.startsWith("idea")) notCompatibleWithConfigurationCache("Intellij does not supports")
}
