@file:Suppress("UnstableApiUsage")

import java.util.*


plugins {
	id("java-library")
	id("maven-publish")
	id("idea")
	id("railx.neoforged.moddev.asDeps")
	id("railx.moddev.platform")
	id("com.gradleup.shadow")
	kotlin("jvm")
}

val buildProps = Properties().apply {
	rootDir.resolve("./build.properties").reader().use { load(it) }
}

val modId = "railx"
version = buildProps["version"]!!

val actualVersion = providers.environmentVariable("project_version")
	.orElse(project.version.toString())

base {
	archivesName = modId
}


modDevPlatform {
	writeProjectDependencies()
	configureShadow(tasks.shadowJar)
}

neoForge {
	enable {}
	
	mods {
		register(modId) {
			sourceSet(sourceSets.main.get())
		}
	}
	
	runs {
		register("client") {
			client()
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
			systemProperty("mixin.debug", "true")
			
			sourceSet = modDevPlatform.modDevRuntime
		}
		
		register("server") {
			server()
			programArgument("--nogui")
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("gameTestServer") {
			type = "gameTestServer"
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("data") {
			data()
			
			// example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
			gameDirectory = project.file("run-data")
			
			// Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
			val existingMods = listOf("create", "railways")
			
			programArguments.addAll(
				"--mod", modId,
				"--all",
				"--output", file("src/generated/resources/").absolutePath,
				"--existing", file("src/main/resources/").absolutePath,
				*existingMods.flatMap { listOf("--existing-mod", it) }.toTypedArray(),
			)
			
			sourceSet = modDevPlatform.modDevRuntime
		}
		
		configureEach {
			// Recommended logging data for a userdev environment
			// The markers can be added/remove as needed separated by commas.
			// "SCAN": For mods scan.
			// "REGISTRIES": For firing of registry events.
			// "REGISTRYDUMP": For getting the contents of all registries.
			systemProperty("forge.logging.markers", "SCAN")
			systemProperty("railx_mixin_bypass", "true")
			systemProperties.put(
				"railx.project_dependencies_file",
				modDevPlatform.projectDependenciesFile.map { it.asFile.absolutePath }
			)
			
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}
}

// Include resources generated by data generators.
sourceSets.main.configure {
	resources.srcDir("src/generated/resources")
}

dependencies {
	val v = libs.versions
	val modDevRuntimeMods = modDevPlatform.modDevRuntimeMods
	
	fun optionalModDependency(dependencyNotation: Any): Dependency? {
		val dependency = compileOnly(dependencyNotation) ?: return null
		return modDevRuntimeMods(dependency)
	}
	
	implementation(projects.minecraft)
	implementation(projects.utils)
	implementation(projects.ccAsm)
	
	implementation("thedarkcolour:kotlinforforge-neoforge:${libs.versions.kotlinForForge.get()}")
	
	implementation("com.simibubi.create:create-${v.minecraft.get()}:${v.create.get()}") {
		isTransitive = false
	}
	
	implementation("net.createmod.ponder:Ponder-NeoForge-${v.minecraft.get()}:${v.ponder.get()}")
	// compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${libs.versions.minecraft.get()}:1.0.4")
	implementation("dev.engine-room.flywheel:flywheel-neoforge-${v.minecraft.get()}:${v.flywheel.get()}")
	implementation("com.tterrag.registrate:Registrate:MC1.21-1.3.0+67")
	
	// for mod compatibility
	optionalModDependency("maven.modrinth:framedblocks:10.4.0")
	optionalModDependency("maven.modrinth:xaeros-world-map:1.39.12_NeoForge_1.21")
	optionalModDependency("maven.modrinth:copycats:3.0.4+mc.1.21.1-neoforge")
	
	// optional mod dependencies
	compileOnly("com.sk89q.worldedit:worldedit-neoforge-mc1.21:7.3.8") {
		exclude(group = "com.google.guava", module = "guava") // version conflict
	}
	
	modDevRuntimeMods("maven.modrinth:worldedit:7.3.8")
}

tasks.jar { isEnabled = false }
tasks.shadowJar {
	archiveVersion = actualVersion
	archiveClassifier = null
}


file("build/mod_output_path.txt").let { output ->
	val jar = tasks.getByName<Jar>("shadowJar")
	if(output.exists()) {
		val copyModJarToServer by tasks.registering(Copy::class) {
			from(jar)
			into(output.readText().trim())
		}
		jar.finalizedBy(copyModJarToServer)
	}
}

// limitation: only optionalMod is supported
tasks.register<Copy>("modJars") {
	from(modDevPlatform.modDevRuntimeMods)
	into(layout.buildDirectory.file("modJars"))
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
	val replaceProperties = mapOf(
		"minecraft_version" to libs.versions.minecraft.get(),
		"minecraft_version_range" to "[1.21.1,1.22)",
		"neo_version" to libs.versions.neoForge.get(),
		"neo_version_range" to "[21,)",
		"loader_version_range" to "[5.3,)",
		"mod_id" to modId,
		"mod_name" to "RailX",
		"mod_license" to "All Rights Reserved",
		"mod_version" to actualVersion,
		"mod_authors" to "lhwdev",
		"mod_description" to "This is good mod",
	)
	inputs.properties(replaceProperties)
	doFirst { expand(inputs.properties) }
	from("src/main/templates")
	into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.configure {
	resources.srcDir(generateModMetadata)
}
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		isDownloadSources = true
		isDownloadJavadoc = true
	}
}

tasks.configureEach {
	if(name.startsWith("idea")) notCompatibleWithConfigurationCache("Intellij does not supports")
}
