@file:Suppress("UnstableApiUsage")

import java.util.*


plugins {
	id("java-library")
	id("maven-publish")
	id("idea")
	id("railx.neoforged.moddev.asDeps")
	id("railx.moddev.platform")
	id("com.gradleup.shadow")
	kotlin("jvm")
}

val buildProps = Properties().apply {
	rootDir.resolve("./build.properties").reader().use { load(it) }
}

val modId = "railx"
version = buildProps["version"]!!

val actualVersion = providers.environmentVariable("project_version")
	.orElse(project.version.toString())

base {
	archivesName = modId
}


modDevPlatform {
	writeProjectDependencies()
	configureShadow(tasks.shadowJar)
}

neoForge {
	enable {}
	
	mods {
		register(modId) {
			sourceSet(sourceSets.main.get())
		}
	}
	
	runs {
		register("client") {
			client()
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
			systemProperty("mixin.debug.export", "true")
		}
		
		register("server") {
			server()
			programArgument("--nogui")
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("gameTestServer") {
			type = "gameTestServer"
			systemProperty("neoforge.enabledGameTestNamespaces", modId)
		}
		
		register("data") {
			data()
			
			// example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
			gameDirectory = project.file("run-data")
			
			// Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
			val existingMods = listOf("create", "railways")
			
			programArguments.addAll(
				"--mod", modId,
				"--all",
				"--output", file("src/generated/resources/").absolutePath,
				"--existing", file("src/main/resources/").absolutePath,
				*existingMods.flatMap { listOf("--existing-mod", it) }.toTypedArray(),
			)
		}
		
		configureEach {
			sourceSet = modDevPlatform.modDevRuntime
			
			// Recommended logging data for a userdev environment
			// The markers can be added/remove as needed separated by commas.
			// "SCAN": For mods scan.
			// "REGISTRIES": For firing of registry events.
			// "REGISTRYDUMP": For getting the contents of all registries.
			systemProperty("forge.logging.markers", "SCAN")
			systemProperty("railx_mixin_bypass", "true")
			systemProperty("mixin.debug.countInjections", "false")
			systemProperties.put(
				"railx.project_dependencies_file",
				modDevPlatform.projectDependenciesFile.map { it.asFile.absolutePath }
			)
			
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}
}

mixin {
	add(sourceSets.main.get(), "railx.refmap.json")
	config("railx.mixins.json")
}

// Include resources generated by data generators.
sourceSets.main.configure {
	resources.srcDir("src/generated/resources")
}

dependencies {
	val v = libs.versions
	val modDevRuntimeMods = modDevPlatform.createRuntimeModConfiguration(modDevPlatform.modDevRuntimeMods.get())
	
	fun optionalModDependency(dependencyNotation: Any): Dependency? {
		val dependency = modCompileOnly(dependencyNotation) ?: return null
		return modDevRuntimeMods(dependency)
	}
	
	implementation(projects.minecraft)
	implementation(projects.utils)
	implementation(projects.ccAsm)
	
	modImplementation("thedarkcolour:kotlinforforge:${libs.versions.kotlinForForge.get()}")
	modImplementation("thedarkcolour:kffmod:${libs.versions.kotlinForForge.get()}") // mod* is not transitive
	modImplementation("thedarkcolour:kfflib:${libs.versions.kotlinForForge.get()}")
	modImplementation("thedarkcolour:kfflang:${libs.versions.kotlinForForge.get()}")
	
	modImplementation("com.simibubi.create:create-${v.minecraft.get()}:${v.create.get()}:slim")
	
	modImplementation("net.createmod.ponder:Ponder-Forge-${v.minecraft.get()}:${v.ponder.get()}")
	// compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${libs.versions.minecraft.get()}:1.0.4")
	modImplementation("dev.engine-room.flywheel:flywheel-forge-${v.minecraft.get()}:${v.flywheel.get()}")
	modImplementation(jarJar("com.tterrag.registrate:Registrate:MC1.20-1.3.11")!!)
	
	// for mod compatibility
	optionalModDependency("com.railwayteam.railways:Steam_Rails-forge-1.20.1:1.7.1+forge-mc1.20.1")
	
	modCompileOnly("de.mrjulsen.mcdragonlib:dragonlib-forge:1.20.1-beta-3.0.28")
	modCompileOnly("de.mrjulsen.paw:pantographsandwires-forge:1.20.1-beta-0.2.3-C6")
	modDevRuntimeMods("maven.modrinth:dragonlib:1.20.1-beta-3.0.28")
	// modDevRuntimeMods("maven.modrinth:create-pantographs-and-wires:1.20.1-beta-0.2.3-C6")
	modDevRuntimeMods("maven.modrinth:architectury-api:9.2.14+forge")
	
	optionalModDependency("maven.modrinth:framedblocks:9.4.2")
	optionalModDependency("maven.modrinth:xaeros-world-map:1.39.12_Forge_1.20")
	optionalModDependency("maven.modrinth:copycats:3.0.4+mc.1.20.1-forge")
	
	// optional mod dependencies
	modCompileOnly(":worldedit:7.2.15") // from flatDir
	modDevRuntimeMods(fileTree("run/mapped-mods"))
	
	implementation(jarJar("io.github.llamalad7:mixinextras-forge:${v.mixinExtras.get()}")!!)
	compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${v.mixinExtras.get()}")!!)
	
	annotationProcessor("org.spongepowered:mixin:0.8.5:processor")
}

tasks.jar { enabled = false }
tasks.shadowJar {
	archiveVersion = actualVersion
	archiveClassifier = null
	
	from(tasks.jarJar)
	from(layout.buildDirectory.dir("mixin").map { it.file("railx.refmap.json") })
	manifest.attributes("MixinConfigs" to "railx.mixins.json")
}

tasks.named("reobfJar") {
	enabled = false
	dependsOn(tasks.shadowJar) // to fix 'uses output of task without declaring an explicit or implicit dependency' error
}

obfuscation {
	reobfuscate(tasks.shadowJar, sourceSets.main.get())
}


file("build/mod_output_path.txt").let { output ->
	val jar = tasks.getByName<Jar>("shadowJar")
	if(output.exists()) {
		val copyModJarToServer by tasks.registering(Copy::class) {
			from(jar)
			into(output.readText().trim())
		}
		jar.finalizedBy(copyModJarToServer)
	}
}

// limitation: only optionalMod is supported
tasks.register<Copy>("modJars") {
	from(modDevPlatform.modDevRuntimeMods)
	into(layout.buildDirectory.file("modJars"))
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
	val replaceProperties = mapOf(
		"minecraft_version" to libs.versions.minecraft.get(),
		"minecraft_version_range" to "[1.20.1,1.20.2)",
		"forge_version_range" to "[${libs.versions.forge.get()},)",
		"loader_version_range" to "[${libs.versions.kotlinForForge.get()},)",
		"mod_id" to modId,
		"mod_name" to "RailX",
		"mod_license" to "All Rights Reserved",
		"mod_version" to actualVersion,
		"mod_authors" to "lhwdev",
		"mod_description" to "This is good mod",
	)
	inputs.properties(replaceProperties)
	doFirst { expand(inputs.properties) }
	from("src/main/templates")
	into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.configure {
	resources.srcDir(generateModMetadata)
}
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		isDownloadSources = true
		isDownloadJavadoc = true
	}
}

tasks.configureEach {
	if(name.startsWith("idea")) notCompatibleWithConfigurationCache("Intellij does not supports")
}
