name: Build
run-name: Build railx for NeoForged 1.21.1
on:
  workflow_dispatch: { }
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read build metadata
        id: meta
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: build.properties
          all: true

      - id: update_version
        name: Update version
        uses: ./tools/create-release
        with:
          tag_format: 'mc1.21.1-$1'
          prerelease: true
          prerelease_suffix: build
          auto_increment_type: prerelease
          tag_schema: semantic
          minimum_version: ${{ steps.meta.outputs.version }}
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build
        run: ./gradlew :forge:build
        env:
          project_version: ${{ steps.update_version.outputs.version }}

      - name: Release build artifacts
        uses: ./tools/create-release
        with:
          prerelease: true
          release_name: RailX {{version}} for NeoForge 1.21.1
          body: |
            Automatic build release.
            This mod is **under development**, so be sure to backup before joining. Might have plenty of bugs.
            
            For Minecraft `1.21.1`, NeoForge `21.1.209+`, Create `6.0.8+`.

            ### Updates
            {{{diff}}}
          artifacts:
            modules/forge/build/libs/*
          github_token: ${{ secrets.GITHUB_TOKEN }}
